name: Docker CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out the repo
        uses: actions/checkout@v3
      - name: Docker Login and setup
        env:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
        run:
          docker login -u $username -p $password
      - name: Build the image
        run: make build
      - name: Push image to Docker Hub
        run: docker push library/lit:latest
